### ISSUE TITLE
No applicable method for "compute-applicable-methods-using-classes" for ccl on OSX.

### ISSUE THREAD

**Issue by Chream** [pcostanza/closer-mop#6] opened 2017-01-05 18:29 UTC
```
(defclass a () ())
(defclass b () ())

(defparameter *a* (make-instance 'a))
(defparameter *b* (make-instance 'b))

(defgeneric foo (x y))

(defmethod foo (x y)
  'yay!)
```

This works. Using the built in function in ccl.
```
(compute-applicable-methods-using-classes (symbol-function 'foo) (list (class-of *a*) (class-of *b*)))
```

This does not work.
```
(closer-mop:compute-applicable-methods-using-classes (symbol-function 'foo) (list (class-of *a*) (class-of *b*)))
```

Going to have a dig into the library later but if someone knows from looking at this a solution is appreciated!

**Comment by Chream** [comment] 2017-01-05 18:51
Backtrace:

```
There is no applicable method for the generic function:
  #<STANDARD-GENERIC-FUNCTION CLOSER-MOP:COMPUTE-APPLICABLE-METHODS-USING-CLASSES #x3020011F152F>
when called with arguments:
  (#<STANDARD-GENERIC-FUNCTION FOO #x30200119050F>
   (#<STANDARD-CLASS A> #<STANDARD-CLASS B>))
   [Condition of type NO-APPLICABLE-METHOD-EXISTS]
```

**Comment by pcostanza** [comment] 2017-01-05 19:34
This is a duplicate of https://github.com/pcostanza/closer-mop/issues/5

**Closed by pcostanza** 2017-01-05 19:34 UTC
